<a href="https://colab.research.google.com/github/DavidCruz1013/datawarehouse-seguros/blob/main/Clientes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/DavidCruz1013/datawarehouse-seguros.git

In [ ]:
import pandas as pd

In [ ]:
url = "https://raw.githubusercontent.com/DavidCruz1013/datawarehouse-seguros/refs/heads/main/data/clientes.csv"

In [ ]:
df = pd.read_csv(url)

**BLOQUE 2** Ecploracion del DataSet

In [ ]:
print("primeras filas del dataset")
display(df.head())

primeras filas del dataset

,id_cliente,nombre,email,genero,fecha_nacimiento,ciudad,segmento
0,1,José Chávez Pérez,jose.chavez.perez1@gmail.com,Hombre,2011/11/24,SanMiguel,NaN
1,2,Daniela Rojas Ortiz,daniela.rojas.ortiz2@seguro.sv,NaN,01-02-80,Sta. Ana,NaN
2,3,Ricardo Cruz Flores,ricardo.cruz.flores3@example.com,Masculino,06-18-79,S. Miguel,NaN
3,4,María Pérez Pérez,maria.perez.perez4@correo.com,Masculino,1960-09-29,LaLibertad,REGULAR
4,5,Fernanda Chávez Rojas,fernanda.chavez.rojas5@seguro.sv,NaN,1945/08/02,San Salvador,Pyme

In [ ]:
print("Dimensiones del data (filas, columnas)")
print(df.shape)

Dimensiones del data (filas, columnas)
(3030, 7)

In [ ]:
print("Columnas del dataset")
print(df.columns)

Columnas del dataset
Index(['id_cliente', 'nombre', 'email', 'genero', 'fecha_nacimiento', 'ciudad',
       'segmento'],
      dtype='object')

In [ ]:
print("valores nulos por columna")
display(df.isnull().sum())

valores nulos por columna

id_cliente            0
nombre                0
email                 0
genero              595
fecha_nacimiento      0
ciudad                0
segmento            597
dtype: int64

In [ ]:
print("Registros duplicados")
print(df.duplicated().sum())

Registros duplicados
0

**      BLOQUE 3 LIMPIEZA DE DATOS**

In [ ]:
#Eliminar espacios al inicio y al final en columna de texto
for col in df.select_dtypes(include=['object']):
    df[col] = df[col].str.strip()

In [ ]:
#normalizar el nombre
df["nombre"]=df["nombre"].str.title()

In [ ]:
#normalizar el nombre
df["email"]=df["email"].str.lower()

In [ ]:
#normalizar el nombre
df["genero"]=df["genero"].str.upper()

In [ ]:
#Convertir fecha de nacimiento a forma fecha
df["fecha_nacimiento"]=pd.to_datetime(df['fecha_nacimiento'],errors="coerce")

In [ ]:
#Normalizar ciudad
df['ciudad']=df["ciudad"].str.title()

In [ ]:
#Limpieza Segmente
df['segmento']=df['segmento'].astype(str)
df['ciudaD']=df['ciudad'].astype(str)
df['segmento']=df['segmento'].str.strip()
df['segmento']=df['segmento'].str.upper()

In [ ]:
for col in df.columns: print(col)

id_cliente
nombre
email
genero
fecha_nacimiento
ciudad
segmento

**  BLOQUE 4: VALIDADCION DE DATOS **

In [ ]:
#crear  columna para registrar errores
df["motivo_rechazo"]= " "

#validar id_cliente
df.loc[df["id_cliente"].isnull(),"motivo_rechazo"] += "id_cliente nulo;"